// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: raspi_services.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaspiService_Start_FullMethodName        = "/raspiservices.RaspiService/Start"
	RaspiService_Stop_FullMethodName         = "/raspiservices.RaspiService/Stop"
	RaspiService_GetStatus_FullMethodName    = "/raspiservices.RaspiService/GetStatus"
	RaspiService_GetFullInfo_FullMethodName  = "/raspiservices.RaspiService/GetFullInfo"
	RaspiService_GetConfig_FullMethodName    = "/raspiservices.RaspiService/GetConfig"
	RaspiService_UpdateConfig_FullMethodName = "/raspiservices.RaspiService/UpdateConfig"
)

// RaspiServiceClient is the client API for RaspiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaspiServiceClient interface {
	Start(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RaspiService, error)
	Stop(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RaspiService, error)
	GetStatus(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RaspiService, error)
	GetFullInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ServiceFullInfo, error)
	GetConfig(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	UpdateConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
}

type raspiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaspiServiceClient(cc grpc.ClientConnInterface) RaspiServiceClient {
	return &raspiServiceClient{cc}
}

func (c *raspiServiceClient) Start(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RaspiService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaspiService)
	err := c.cc.Invoke(ctx, RaspiService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raspiServiceClient) Stop(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RaspiService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaspiService)
	err := c.cc.Invoke(ctx, RaspiService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raspiServiceClient) GetStatus(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*RaspiService, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RaspiService)
	err := c.cc.Invoke(ctx, RaspiService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raspiServiceClient) GetFullInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ServiceFullInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceFullInfo)
	err := c.cc.Invoke(ctx, RaspiService_GetFullInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raspiServiceClient) GetConfig(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, RaspiService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raspiServiceClient) UpdateConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, RaspiService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaspiServiceServer is the server API for RaspiService service.
// All implementations must embed UnimplementedRaspiServiceServer
// for forward compatibility.
type RaspiServiceServer interface {
	Start(context.Context, *EmptyRequest) (*RaspiService, error)
	Stop(context.Context, *EmptyRequest) (*RaspiService, error)
	GetStatus(context.Context, *EmptyRequest) (*RaspiService, error)
	GetFullInfo(context.Context, *EmptyRequest) (*ServiceFullInfo, error)
	GetConfig(context.Context, *EmptyRequest) (*ConfigResponse, error)
	UpdateConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	mustEmbedUnimplementedRaspiServiceServer()
}

// UnimplementedRaspiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaspiServiceServer struct{}

func (UnimplementedRaspiServiceServer) Start(context.Context, *EmptyRequest) (*RaspiService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedRaspiServiceServer) Stop(context.Context, *EmptyRequest) (*RaspiService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedRaspiServiceServer) GetStatus(context.Context, *EmptyRequest) (*RaspiService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedRaspiServiceServer) GetFullInfo(context.Context, *EmptyRequest) (*ServiceFullInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFullInfo not implemented")
}
func (UnimplementedRaspiServiceServer) GetConfig(context.Context, *EmptyRequest) (*ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedRaspiServiceServer) UpdateConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedRaspiServiceServer) mustEmbedUnimplementedRaspiServiceServer() {}
func (UnimplementedRaspiServiceServer) testEmbeddedByValue()                      {}

// UnsafeRaspiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaspiServiceServer will
// result in compilation errors.
type UnsafeRaspiServiceServer interface {
	mustEmbedUnimplementedRaspiServiceServer()
}

func RegisterRaspiServiceServer(s grpc.ServiceRegistrar, srv RaspiServiceServer) {
	// If the following call pancis, it indicates UnimplementedRaspiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaspiService_ServiceDesc, srv)
}

func _RaspiService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaspiServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaspiService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaspiServiceServer).Start(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaspiService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaspiServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaspiService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaspiServiceServer).Stop(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaspiService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaspiServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaspiService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaspiServiceServer).GetStatus(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaspiService_GetFullInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaspiServiceServer).GetFullInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaspiService_GetFullInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaspiServiceServer).GetFullInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaspiService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaspiServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaspiService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaspiServiceServer).GetConfig(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaspiService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaspiServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaspiService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaspiServiceServer).UpdateConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaspiService_ServiceDesc is the grpc.ServiceDesc for RaspiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaspiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raspiservices.RaspiService",
	HandlerType: (*RaspiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _RaspiService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _RaspiService_Stop_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _RaspiService_GetStatus_Handler,
		},
		{
			MethodName: "GetFullInfo",
			Handler:    _RaspiService_GetFullInfo_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _RaspiService_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _RaspiService_UpdateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raspi_services.proto",
}
