// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: sys_info.proto

package sysinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_sys_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SisInfo *SysInfo `protobuf:"bytes,1,opt,name=sisInfo,proto3" json:"sisInfo,omitempty"`
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_sys_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetSisInfo() *SysInfo {
	if x != nil {
		return x.SisInfo
	}
	return nil
}

type SysInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiskInfo *DiskInfo `protobuf:"bytes,1,opt,name=diskInfo,proto3" json:"diskInfo,omitempty"`
	NetInfo  *NetInfo  `protobuf:"bytes,2,opt,name=netInfo,proto3" json:"netInfo,omitempty"`
	FanInfo  *FanInfo  `protobuf:"bytes,3,opt,name=fanInfo,proto3" json:"fanInfo,omitempty"`
	MemInfo  *MemInfo  `protobuf:"bytes,4,opt,name=memInfo,proto3" json:"memInfo,omitempty"`
	CpuInfo  *CpuInfo  `protobuf:"bytes,5,opt,name=cpuInfo,proto3" json:"cpuInfo,omitempty"`
}

func (x *SysInfo) Reset() {
	*x = SysInfo{}
	mi := &file_sys_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfo) ProtoMessage() {}

func (x *SysInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfo.ProtoReflect.Descriptor instead.
func (*SysInfo) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{2}
}

func (x *SysInfo) GetDiskInfo() *DiskInfo {
	if x != nil {
		return x.DiskInfo
	}
	return nil
}

func (x *SysInfo) GetNetInfo() *NetInfo {
	if x != nil {
		return x.NetInfo
	}
	return nil
}

func (x *SysInfo) GetFanInfo() *FanInfo {
	if x != nil {
		return x.FanInfo
	}
	return nil
}

func (x *SysInfo) GetMemInfo() *MemInfo {
	if x != nil {
		return x.MemInfo
	}
	return nil
}

func (x *SysInfo) GetCpuInfo() *CpuInfo {
	if x != nil {
		return x.CpuInfo
	}
	return nil
}

type NetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetUp   string `protobuf:"bytes,1,opt,name=NetUp,proto3" json:"NetUp,omitempty"`
	NetDown string `protobuf:"bytes,2,opt,name=NetDown,proto3" json:"NetDown,omitempty"`
}

func (x *NetInfo) Reset() {
	*x = NetInfo{}
	mi := &file_sys_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetInfo) ProtoMessage() {}

func (x *NetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetInfo.ProtoReflect.Descriptor instead.
func (*NetInfo) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{3}
}

func (x *NetInfo) GetNetUp() string {
	if x != nil {
		return x.NetUp
	}
	return ""
}

func (x *NetInfo) GetNetDown() string {
	if x != nil {
		return x.NetDown
	}
	return ""
}

type MemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemPercent string `protobuf:"bytes,1,opt,name=MemPercent,proto3" json:"MemPercent,omitempty"`
	MemUsed    string `protobuf:"bytes,2,opt,name=MemUsed,proto3" json:"MemUsed,omitempty"`
	MemTotal   string `protobuf:"bytes,3,opt,name=MemTotal,proto3" json:"MemTotal,omitempty"`
}

func (x *MemInfo) Reset() {
	*x = MemInfo{}
	mi := &file_sys_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemInfo) ProtoMessage() {}

func (x *MemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemInfo.ProtoReflect.Descriptor instead.
func (*MemInfo) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{4}
}

func (x *MemInfo) GetMemPercent() string {
	if x != nil {
		return x.MemPercent
	}
	return ""
}

func (x *MemInfo) GetMemUsed() string {
	if x != nil {
		return x.MemUsed
	}
	return ""
}

func (x *MemInfo) GetMemTotal() string {
	if x != nil {
		return x.MemTotal
	}
	return ""
}

type USBDrive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Used  string `protobuf:"bytes,2,opt,name=Used,proto3" json:"Used,omitempty"`
	Total string `protobuf:"bytes,3,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *USBDrive) Reset() {
	*x = USBDrive{}
	mi := &file_sys_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *USBDrive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*USBDrive) ProtoMessage() {}

func (x *USBDrive) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use USBDrive.ProtoReflect.Descriptor instead.
func (*USBDrive) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{5}
}

func (x *USBDrive) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *USBDrive) GetUsed() string {
	if x != nil {
		return x.Used
	}
	return ""
}

func (x *USBDrive) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type DiskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RootUsed  string      `protobuf:"bytes,1,opt,name=RootUsed,proto3" json:"RootUsed,omitempty"`
	RootTotal string      `protobuf:"bytes,2,opt,name=RootTotal,proto3" json:"RootTotal,omitempty"`
	USBDrives []*USBDrive `protobuf:"bytes,3,rep,name=USBDrives,proto3" json:"USBDrives,omitempty"`
}

func (x *DiskInfo) Reset() {
	*x = DiskInfo{}
	mi := &file_sys_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskInfo) ProtoMessage() {}

func (x *DiskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskInfo.ProtoReflect.Descriptor instead.
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{6}
}

func (x *DiskInfo) GetRootUsed() string {
	if x != nil {
		return x.RootUsed
	}
	return ""
}

func (x *DiskInfo) GetRootTotal() string {
	if x != nil {
		return x.RootTotal
	}
	return ""
}

func (x *DiskInfo) GetUSBDrives() []*USBDrive {
	if x != nil {
		return x.USBDrives
	}
	return nil
}

type CpuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuTemp      string   `protobuf:"bytes,1,opt,name=CpuTemp,proto3" json:"CpuTemp,omitempty"`
	CoreInfoList []string `protobuf:"bytes,2,rep,name=CoreInfoList,proto3" json:"CoreInfoList,omitempty"`
}

func (x *CpuInfo) Reset() {
	*x = CpuInfo{}
	mi := &file_sys_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuInfo) ProtoMessage() {}

func (x *CpuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuInfo.ProtoReflect.Descriptor instead.
func (*CpuInfo) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{7}
}

func (x *CpuInfo) GetCpuTemp() string {
	if x != nil {
		return x.CpuTemp
	}
	return ""
}

func (x *CpuInfo) GetCoreInfoList() []string {
	if x != nil {
		return x.CoreInfoList
	}
	return nil
}

type FanInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FanSpeed  string `protobuf:"bytes,1,opt,name=FanSpeed,proto3" json:"FanSpeed,omitempty"`
	FanStatus bool   `protobuf:"varint,2,opt,name=FanStatus,proto3" json:"FanStatus,omitempty"`
}

func (x *FanInfo) Reset() {
	*x = FanInfo{}
	mi := &file_sys_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanInfo) ProtoMessage() {}

func (x *FanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sys_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanInfo.ProtoReflect.Descriptor instead.
func (*FanInfo) Descriptor() ([]byte, []int) {
	return file_sys_info_proto_rawDescGZIP(), []int{8}
}

func (x *FanInfo) GetFanSpeed() string {
	if x != nil {
		return x.FanSpeed
	}
	return ""
}

func (x *FanInfo) GetFanStatus() bool {
	if x != nil {
		return x.FanStatus
	}
	return false
}

var File_sys_info_proto protoreflect.FileDescriptor

var file_sys_info_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x79, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x35, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x07, 0x73, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x73, 0x69, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xc0, 0x01, 0x0a, 0x07, 0x53, 0x79,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x07,
	0x6e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x4e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x22, 0x0a, 0x07, 0x66, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x46, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x66, 0x61, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x6d, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x07, 0x63, 0x70, 0x75, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x70, 0x75, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x63, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x39, 0x0a, 0x07,
	0x4e, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x65, 0x74, 0x55, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x65, 0x74, 0x55, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x4e, 0x65, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4e, 0x65, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x22, 0x5f, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x6d, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x4d, 0x65, 0x6d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x4d, 0x65, 0x6d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x48, 0x0a, 0x08, 0x55, 0x53, 0x42, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x6d, 0x0a, 0x08, 0x44, 0x69, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x74, 0x55, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x52, 0x6f, 0x6f, 0x74, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x6f,
	0x6f, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52,
	0x6f, 0x6f, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x09, 0x55, 0x53, 0x42, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x53,
	0x42, 0x44, 0x72, 0x69, 0x76, 0x65, 0x52, 0x09, 0x55, 0x53, 0x42, 0x44, 0x72, 0x69, 0x76, 0x65,
	0x73, 0x22, 0x47, 0x0a, 0x07, 0x43, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x70, 0x75, 0x54, 0x65, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x70, 0x75, 0x54, 0x65, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x72, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x07, 0x46, 0x61,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x61, 0x6e, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x61, 0x6e, 0x53, 0x70, 0x65, 0x65,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x46, 0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32,
	0x40, 0x0a, 0x0e, 0x53, 0x79, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x6f, 0x6e, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x69, 0x6e, 0x66, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sys_info_proto_rawDescOnce sync.Once
	file_sys_info_proto_rawDescData = file_sys_info_proto_rawDesc
)

func file_sys_info_proto_rawDescGZIP() []byte {
	file_sys_info_proto_rawDescOnce.Do(func() {
		file_sys_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_info_proto_rawDescData)
	})
	return file_sys_info_proto_rawDescData
}

var file_sys_info_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sys_info_proto_goTypes = []any{
	(*GetInfoRequest)(nil),  // 0: GetInfoRequest
	(*GetInfoResponse)(nil), // 1: GetInfoResponse
	(*SysInfo)(nil),         // 2: SysInfo
	(*NetInfo)(nil),         // 3: NetInfo
	(*MemInfo)(nil),         // 4: MemInfo
	(*USBDrive)(nil),        // 5: USBDrive
	(*DiskInfo)(nil),        // 6: DiskInfo
	(*CpuInfo)(nil),         // 7: CpuInfo
	(*FanInfo)(nil),         // 8: FanInfo
}
var file_sys_info_proto_depIdxs = []int32{
	2, // 0: GetInfoResponse.sisInfo:type_name -> SysInfo
	6, // 1: SysInfo.diskInfo:type_name -> DiskInfo
	3, // 2: SysInfo.netInfo:type_name -> NetInfo
	8, // 3: SysInfo.fanInfo:type_name -> FanInfo
	4, // 4: SysInfo.memInfo:type_name -> MemInfo
	7, // 5: SysInfo.cpuInfo:type_name -> CpuInfo
	5, // 6: DiskInfo.USBDrives:type_name -> USBDrive
	0, // 7: SysInfoService.GetInfo:input_type -> GetInfoRequest
	1, // 8: SysInfoService.GetInfo:output_type -> GetInfoResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sys_info_proto_init() }
func file_sys_info_proto_init() {
	if File_sys_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sys_info_proto_goTypes,
		DependencyIndexes: file_sys_info_proto_depIdxs,
		MessageInfos:      file_sys_info_proto_msgTypes,
	}.Build()
	File_sys_info_proto = out.File
	file_sys_info_proto_rawDesc = nil
	file_sys_info_proto_goTypes = nil
	file_sys_info_proto_depIdxs = nil
}
