// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Infobar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"stats stats-vertical lg:stats-horizontal shadow\" id=\"info_bar\" hx-swap-oob=\"true\"><div class=\"stat\"><div class=\"stat-title\">SD CARD</div><div class=\"stat-value text-2xl\">86GB/116GB</div></div><div class=\"stat\"><div class=\"stat-title\">Toshiba</div><div class=\"stat-value text-2xl\">634GB/953GB</div></div><div class=\"stat\"><div class=\"stat-title\">Ram Usage</div><div class=\"stat-value text-2xl\">953mb/3945mb (29.2%)</div><div class=\"stat-title\">Net Speed</div><div class=\"stat-value text-2xl\">&#8593; 0,23kb &#8595; 0,64kb</div></div><div class=\"stat\"><div class=\"stat-title\">Cpu Usage</div><div class=\"stat-value text-2xl\">1.23% 2.64% 0.01% 5.32%</div><div class=\"stat-title\">Cpu Temp</div><div class=\"stat-value text-2xl\">56°C</div></div><div class=\"stat\"><div class=\"stat-title\">Vent Status</div><div class=\"stat-value text-success text-2xl\">[on]</div><div class=\"stat-title\">Vent Speed</div><div class=\"stat-value text-2xl\">2395rpm</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
